-- MySQL Script generated by MySQL Workbench
-- Wed Mar 25 20:35:13 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Medico` (
  `ID_medico` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `CRM` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_medico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Paciente` (
  `ID_paciente` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `Data_nascimento` DATE NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `rg` VARCHAR(11) NOT NULL,
  `CPF` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`ID_paciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Consulta` (
  `ID_consulta` INT NOT NULL,
  `horario` VARCHAR(45) NOT NULL,
  `data` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `motivo` VARCHAR(45) NOT NULL,
  `Medico_ID_medico` INT NOT NULL,
  `Paciente_ID_paciente` INT NOT NULL,
  PRIMARY KEY (`ID_consulta`),
  INDEX `fk_Consulta_Medico1_idx` (`Medico_ID_medico` ASC) VISIBLE,
  INDEX `fk_Consulta_Paciente1_idx` (`Paciente_ID_paciente` ASC) VISIBLE,
  CONSTRAINT `fk_Consulta_Medico1`
    FOREIGN KEY (`Medico_ID_medico`)
    REFERENCES `mydb`.`Medico` (`ID_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Consulta_Paciente1`
    FOREIGN KEY (`Paciente_ID_paciente`)
    REFERENCES `mydb`.`Paciente` (`ID_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`exame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`exame` (
  `ID_exame` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descriçao` VARCHAR(200) NULL,
  `Paciente_ID_paciente` INT NOT NULL,
  PRIMARY KEY (`ID_exame`),
  INDEX `fk_exame_Paciente1_idx` (`Paciente_ID_paciente` ASC) VISIBLE,
  CONSTRAINT `fk_exame_Paciente1`
    FOREIGN KEY (`Paciente_ID_paciente`)
    REFERENCES `mydb`.`Paciente` (`ID_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`especialidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`especialidade` (
  `ID_especialidade` INT NOT NULL,
  `Nome_especialidade` VARCHAR(45) NOT NULL,
  `Medico_ID_medico` INT NOT NULL,
  PRIMARY KEY (`ID_especialidade`),
  INDEX `fk_especialidade_Medico1_idx` (`Medico_ID_medico` ASC) VISIBLE,
  CONSTRAINT `fk_especialidade_Medico1`
    FOREIGN KEY (`Medico_ID_medico`)
    REFERENCES `mydb`.`Medico` (`ID_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `ID_usuario` INT NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `usuariocol` VARCHAR(45) NOT NULL,
  `Paciente_ID_paciente` INT NOT NULL,
  PRIMARY KEY (`ID_usuario`),
  INDEX `fk_usuario_Paciente1_idx` (`Paciente_ID_paciente` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_Paciente1`
    FOREIGN KEY (`Paciente_ID_paciente`)
    REFERENCES `mydb`.`Paciente` (`ID_paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`resultado_exame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resultado_exame` (
  `ID_result_exame` INT NOT NULL,
  `resultado` VARCHAR(400) NOT NULL,
  `exame_ID_exame` INT NOT NULL,
  PRIMARY KEY (`ID_result_exame`),
  INDEX `fk_resultado_exame_exame1_idx` (`exame_ID_exame` ASC) VISIBLE,
  CONSTRAINT `fk_resultado_exame_exame1`
    FOREIGN KEY (`exame_ID_exame`)
    REFERENCES `mydb`.`exame` (`ID_exame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clinica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clinica` (
  `ID_clinica` INT NOT NULL,
  `Nome_clinica` VARCHAR(45) NOT NULL,
  `endereço` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `Medico_ID_medico` INT NOT NULL,
  PRIMARY KEY (`ID_clinica`),
  INDEX `fk_clinica_Medico_idx` (`Medico_ID_medico` ASC) VISIBLE,
  CONSTRAINT `fk_clinica_Medico`
    FOREIGN KEY (`Medico_ID_medico`)
    REFERENCES `mydb`.`Medico` (`ID_medico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
